SELECT 
    ROW_NUMBER() OVER(ORDER BY PERSONEL_ADI) AS RN_AD,
	ROW_NUMBER() OVER(ORDER BY PERSONEL_SOYADI) AS RN_SOYAD,
	RANK() OVER(ORDER BY PERSONEL_ADI) AS RN_RANK,
	DENSE_RANK() OVER(ORDER BY PERSONEL_ADI) AS RN_DENSRANK,
    *
	
FROM IK_PERSONEL