/*

---------SQL FUNCTÝONS------

*/ 

--CONVERT(int,'10')  tip dönüþümü yapar
--CAST('10' AS INT)  tip dönüþümü yapar
--SUBSTRING('AHMET',3,3) MET ekrana yazdýrýr
--REPLACE('AHMET','T','D') deðiþtirir AHMED yazar

--UPPER/LOWER

SELECT
    PERSONEL_SOYADI,
	UPPER(PERSONEL_SOYADI) AS PERSONEL_SOYADI_UPPER,
	LOWER(PERSONEL_SOYADI) AS PERSONEL_SOYADI_LOWER
FROM 
    IK_PERSONEL

--LTRIM/RTRIM/TRIM


SELECT
    PERSONEL_ADI, /*   Ahmet   */
	RTRIM(PERSONEL_ADI) AS PERSONEL_ADI_RTRIM,/*   Ahmet*/
	LTRIM(PERSONEL_ADI) AS PERSONEL_ADI_LTRIM,/*Ahmet   */
	TRIM(PERSONEL_ADI) AS PERSONEL_ADI_TRIM/*Ahmet*/
	
FROM 
    IK_PERSONEL

--Floor, ceiling, round

SELECT
   FLOOR(24.1) AS FLOOR_COLUMN,
   CEILING(24.1) AS CEILING_COLUMN,
   ROUND(24.956,3) AS ROUND_COLUMN_3,
   ROUND(24.956,2) AS ROUND_COLUMN_2,
   ROUND(24.956,1) AS ROUND_COLUMN_1,
   ROUND(24.956,0) AS ROUND_COLUMN_0

--DATEADD

SELECT
   GETDATE() AS NOW_DATE,
   DATEADD(DAY, 1, GETDATE()) AS NEW_DATE1,
   DATEADD(MONTH, 1, GETDATE()) AS NEW_DATE2,
   DATEADD(YEAR, 1, GETDATE()) AS NEW_DATE3

--DATEIFF FARKINI GETÝRÝ
--DATEPART